export type AiMode = "minutes" | "summary" | "brainstorm";

/** Deterministic demo output used when no ANTHROPIC_API_KEY is configured (and by the static demo build). */
export function demoAiOutput(mode: AiMode, title: string, input: string, locale: string): string {
  const faDemo: Record<AiMode, string> = {
    minutes: `# صورت‌جلسه: ${title}\n\n**تاریخ:** ${new Date().toLocaleDateString("fa-IR")}\n\n## دستور جلسه\n- مرور پیشرفت نسخه ۱.۰ آسامیت\n- برنامه‌ریزی انتشار عمومی و دموی محصول\n\n## خلاصه مذاکرات\n- اعضای تیم وضعیت بخش‌های پیام‌رسان، جلسات و پنل مدیریت را ارائه کردند.\n- طراحی گلاسمورفیسم و لوگوی جدید به تأیید نهایی رسید.\n\n## تصمیمات\n۱. انتشار نسخه عمومی طبق زمان‌بندی انجام شود.\n۲. بازخورد کاربران در گروه «تیم محصول» جمع‌آوری شود.\n\n## اقدامات\n- [ ] آماده‌سازی محیط دمو — مسئول: تیم زیرساخت\n- [ ] تهیه ویدیوی معرفی — مسئول: تیم محصول\n\n---\n*این خروجی نمونهٔ حالت دمو است؛ با تنظیم کلید API، صورت‌جلسه واقعی از محتوای جلسه تولید می‌شود.*`,
    summary: `# خلاصه جلسه: ${title}\n\n- پیشرفت نسخه ۱.۰ مرور شد و همه بخش‌ها آماده انتشار هستند.\n- طراحی نهایی (گلاسمورفیسم + لوگو) تأیید شد.\n- جمع‌بندی: انتشار طبق برنامه؛ تمرکز بعدی روی بازخورد کاربران.\n\n**گام‌های بعدی:** آماده‌سازی دمو و ویدیوی معرفی.\n\n---\n*خروجی نمونهٔ حالت دمو — برای خلاصه واقعی، کلید API را تنظیم کنید.*`,
    brainstorm: `# هم‌فکری: ${input || title}\n\n## ایده‌های ارتباطی\n۱. **اتاق‌های موضوعی زنده** — گفت‌وگوهای صوتی باز مثل رادیو تیمی.\n۲. **واکنش‌های هوشمند** — پیشنهاد واکنش بر اساس محتوای پیام.\n\n## ایده‌های هوش مصنوعی\n۳. **ترجمه همزمان جلسات** — هر شرکت‌کننده به زبان خودش بشنود.\n۴. **کارت اقدام خودکار** — تبدیل جمله «باید انجام بدیم» به تسک.\n\n## ایده‌های آموزشی\n۵. **آزمون سریع در کلاس** — سوال چهارگزینه‌ای حین تدریس.\n۶. **گزارش پیشرفت هفتگی** — خلاصه خودکار برای والدین/مدیران.\n\n**پیشنهاد برتر:** ایده‌های ۳ و ۴ بیشترین ارزش فوری را دارند.\n\n---\n*خروجی نمونهٔ حالت دمو — برای هم‌فکری واقعی، کلید API را تنظیم کنید.*`,
  };
  const enDemo: Record<AiMode, string> = {
    minutes: `# Meeting Minutes: ${title}\n\n**Date:** ${new Date().toLocaleDateString("en-US")}\n\n## Agenda\n- Asameet v1.0 progress review\n- Public launch & demo planning\n\n## Discussion\n- Team presented status of messenger, meetings and admin panel.\n- Glassmorphism design and the new logo received final approval.\n\n## Decisions\n1. Ship the public release on schedule.\n2. Collect user feedback in the "Product Team" group.\n\n## Action items\n- [ ] Prepare the demo environment — owner: infra team\n- [ ] Produce the intro video — owner: product team\n\n---\n*Demo-mode sample output; configure an API key for real minutes generated from your meeting content.*`,
    summary: `# Summary: ${title}\n\n- v1.0 progress reviewed; all modules ready for release.\n- Final design (glassmorphism + logo) approved.\n- Conclusion: release on schedule; next focus is user feedback.\n\n**Next steps:** prepare the demo and the intro video.\n\n---\n*Demo-mode sample output — configure an API key for real summaries.*`,
    brainstorm: `# Brainstorm: ${input || title}\n\n## Communication ideas\n1. **Live topic rooms** — open audio spaces like a team radio.\n2. **Smart reactions** — reaction suggestions based on message content.\n\n## AI ideas\n3. **Real-time meeting translation** — everyone hears their own language.\n4. **Auto action cards** — turn "we should do X" into a task.\n\n## Education ideas\n5. **In-class quick quiz** — multiple-choice questions while teaching.\n6. **Weekly progress digest** — automatic summary for parents/managers.\n\n**Top picks:** ideas 3 and 4 deliver the most immediate value.\n\n---\n*Demo-mode sample output — configure an API key for real brainstorming.*`,
  };
  return (locale === "fa" || locale === "ar" ? faDemo : enDemo)[mode];
}
