#!/usr/bin/env bash
#
# Generate every secret the stack needs, once, into deploy/.env.
#
# Self-hosted Supabase ships with example keys in its documentation, and those
# keys are signed with a JWT secret that is printed in that same documentation.
# A stack left on them is a stack anyone on the internet can read and write as
# `service_role`. This exists so that never happens here: it refuses to run
# twice, and it refuses to write a key it did not generate itself.
#
# The two API keys are not random strings — they are JWTs signed with the same
# secret GoTrue and PostgREST verify against, so they have to be minted, not
# invented. That is done below in pure shell + openssl rather than by pulling a
# Node or Python toolchain onto the server for one job.
#
#   ./deploy/scripts/gen-secrets.sh
set -Eeuo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$HERE/.env"

if [[ -f "$ENV_FILE" ]]; then
  echo "✗ $ENV_FILE already exists." >&2
  echo "  Refusing to overwrite it — regenerating secrets invalidates every" >&2
  echo "  session and every stored password hash reference. To start over," >&2
  echo "  move the file aside deliberately." >&2
  exit 1
fi

command -v openssl >/dev/null || { echo "✗ openssl is required" >&2; exit 1; }

# base64url, no padding — what JWT requires and what plain base64 is not.
b64url() { openssl base64 -A | tr '+/' '-_' | tr -d '='; }

mint_jwt() {
  local role="$1" secret="$2" iat exp header payload signing
  iat="$(date +%s)"
  # Ten years. These are deployment keys rotated by re-running this script and
  # rebuilding, not session tokens; a short expiry here would silently break the
  # whole site on an ordinary Tuesday.
  exp="$(( iat + 60*60*24*3650 ))"
  header="$(printf '{"alg":"HS256","typ":"JWT"}' | b64url)"
  payload="$(printf '{"role":"%s","iss":"supabase","iat":%s,"exp":%s}' "$role" "$iat" "$exp" | b64url)"
  signing="${header}.${payload}"
  printf '%s.%s' "$signing" \
    "$(printf '%s' "$signing" | openssl dgst -binary -sha256 -hmac "$secret" | b64url)"
}

# Alphanumeric only. Postgres and several of these services carry their
# passwords inside URLs, and a `/` or `@` in a password turns a connection
# string into a different connection string.
#
# Written without a trailing `head` on purpose. The obvious
# `tr -dc … </dev/urandom | head -c 48` kills `tr` with SIGPIPE the moment head
# has enough, and under `set -o pipefail` that aborts the whole script — which
# is exactly what happened the first time this ran. Here `head` reads a fixed
# number of bytes and exits first, `tr` consumes all of them and exits
# normally, and bash does the trimming with no pipe in sight.
rand_alnum() {
  local n="${1:-48}" raw
  raw="$(head -c "$(( n * 8 ))" /dev/urandom | LC_ALL=C tr -dc 'A-Za-z0-9')"
  if (( ${#raw} < n )); then
    echo "✗ could not read enough entropy from /dev/urandom" >&2
    exit 1
  fi
  printf '%s' "${raw:0:n}"
}

JWT_SECRET="$(rand_alnum 64)"
POSTGRES_PASSWORD="$(rand_alnum 48)"
ANON_KEY="$(mint_jwt anon "$JWT_SECRET")"
SERVICE_ROLE_KEY="$(mint_jwt service_role "$JWT_SECRET")"
# Realtime insists on exactly sixteen bytes for its column encryption key and
# a long one for the Phoenix session secret. Wrong lengths are a crash loop at
# boot, not a warning.
REALTIME_ENC_KEY="$(rand_alnum 16)"
REALTIME_SECRET_KEY_BASE="$(rand_alnum 64)"
REALTIME_METRICS_SECRET="$(rand_alnum 48)"

umask 077
cat > "$ENV_FILE" <<ENV
# Generated by deploy/scripts/gen-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# This file is the whole security of the deployment. It is 0600 and owned by
# root, it is in .gitignore, and it must never be pasted into a chat window, a
# support ticket or a screenshot. Back it up somewhere you control — losing it
# means every session and every stored token becomes unverifiable.

# ── Identity of this deployment ──────────────────────────────────────────────
# Set these two by hand before the first deploy.
DOMAIN=
# Where Let's Encrypt sends expiry warnings. A real mailbox somebody reads.
ACME_EMAIL=

# ── Secrets (generated — do not edit) ────────────────────────────────────────
JWT_SECRET=$JWT_SECRET
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
ANON_KEY=$ANON_KEY
SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY
REALTIME_ENC_KEY=$REALTIME_ENC_KEY
REALTIME_SECRET_KEY_BASE=$REALTIME_SECRET_KEY_BASE
REALTIME_METRICS_SECRET=$REALTIME_METRICS_SECRET

# ── SMS ──────────────────────────────────────────────────────────────────────
# The Kavenegar API key, not the panel password. Paste it here and nowhere else.
KAVENEGAR_API_KEY=
KAVENEGAR_SENDER=
SMS_OTP_PATTERN=
SMS_PROVIDER=kavenegar

# ── Backups ──────────────────────────────────────────────────────────────────
# A passphrase for the encrypted nightly dump. Keep a copy off this machine: a
# backup you cannot decrypt is not a backup.
BACKUP_PASSPHRASE=$(rand_alnum 40)
BACKUP_KEEP_DAYS=30

# ── Where base images come from ──────────────────────────────────────────────
# Docker Hub refuses connections from Iranian addresses. preflight.sh reports
# which mirrors answer from this machine; put the winner here.
BASE_REGISTRY=docker.io

# ── Health alerts ────────────────────────────────────────────────────────────
# A mobile number to text when the site stops answering. Blank disables it.
ALERT_PHONE=
ENV

chmod 600 "$ENV_FILE"
echo "✓ wrote $ENV_FILE (0600)"
echo
echo "  Now fill in, by hand:  DOMAIN  ACME_EMAIL  KAVENEGAR_API_KEY"
echo "  And keep a copy of this file somewhere safe and off this machine."
