-- order_events.created_at is now(), the *transaction* timestamp, so every event
-- written in one transaction shares it. That happens on the normal path:
-- submitting an order also routes it, so `submitted` and `matching` carry the
-- same created_at and the timeline was free to render them in either order —
-- including backwards, which reads as an order routed before it was submitted.
--
-- A sequence settles it. It is insertion order, which is what a timeline means,
-- and it stays correct however coarse the clock is.

alter table public.order_events add column seq bigint generated by default as identity;
create index order_events_order_seq on public.order_events (order_id, seq);
