-- 0018 — Phase 7: the shareable status page, tiers, and referrals
--
--   §17.2  a recipient abroad follows the transfer without an account
--   §17.8  volume tiers, surfaced as visible progress rather than a silent perk
--   §17.9  a referral that pays out on the referee's first *completed* order

-- ─────────────────────────────────────────────────────────────────────────────
-- A. Public status (§17.2)
--
-- The public reference is a display identifier, not a secret — six characters
-- from a 32-symbol alphabet is about a billion values, which is plenty against
-- a person and not much against a script. So the lookup carries its own
-- ceiling, and the ceiling is on things a caller cannot lie about: total
-- lookups in the last hour, and lookups of one reference in the last hour. An
-- IP-based limit would have been spoofable by whoever bothered.
--
-- What comes back is deliberately thin: the state, the dates, the corridor,
-- what the recipient is waiting for, and which office is handling it. No names,
-- no account details, no fees, no Toman leg, no sender. Enough to answer "where
-- is my money", and not enough to be worth guessing for.
-- ─────────────────────────────────────────────────────────────────────────────

create table public.public_lookups (
  id bigint generated by default as identity primary key,
  public_ref text not null,
  found boolean not null,
  created_at timestamptz not null default now()
);
create index public_lookups_recent on public.public_lookups (created_at desc);
create index public_lookups_ref on public.public_lookups (public_ref, created_at desc);
alter table public.public_lookups enable row level security;
create policy public_lookups_staff_read on public.public_lookups
  for select using (public.is_platform_staff());

create or replace function public.order_public_status(p_ref text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  o public.orders%rowtype;
  v_ref text := upper(btrim(coalesce(p_ref, '')));
  v_office_fa text;
  v_office_en text;
begin
  if v_ref !~ '^ASA-[0-9A-Z]{6}$' then
    return jsonb_build_object('found', false);
  end if;

  if (select count(*) from public.public_lookups where created_at > now() - interval '1 hour') > 600 then
    raise exception 'too many status lookups right now; try again shortly';
  end if;
  if (select count(*) from public.public_lookups
       where public_ref = v_ref and created_at > now() - interval '1 hour') > 60 then
    raise exception 'too many lookups for that reference; try again shortly';
  end if;

  select * into o from public.orders where public_ref = v_ref and deleted_at is null;
  -- Logged whether or not it hit, because a wall of misses is what enumeration
  -- looks like and the ceiling above has to be able to see it.
  insert into public.public_lookups (public_ref, found) values (v_ref, o.id is not null);
  if o.id is null then
    return jsonb_build_object('found', false);
  end if;

  select e.legal_name_fa, e.legal_name_en into v_office_fa, v_office_en
    from public.exchange_offices e where e.id = o.office_id;

  return jsonb_build_object(
    'found', true,
    'public_ref', o.public_ref,
    'state', o.state,
    'corridor', o.corridor,
    'receive_currency', o.receive_currency,
    'receive_amount_minor', o.receive_amount_minor,
    'created_at', o.created_at,
    'state_since', o.state_since,
    'sla_target_at', o.sla_target_at,
    'due_at', o.due_at,
    'office_fa', v_office_fa,
    'office_en', v_office_en,
    'timeline', coalesce((
      select jsonb_agg(jsonb_build_object('to_state', ev.to_state, 'at', ev.created_at) order by ev.seq)
        from public.order_events ev where ev.order_id = o.id
    ), '[]'::jsonb)
  );
end $$;

revoke all on function public.order_public_status(text) from public, anon, authenticated;
grant execute on function public.order_public_status(text) to anon, authenticated;

-- ─────────────────────────────────────────────────────────────────────────────
-- B. Customer tiers (§17.8)
--
-- Volume is derived from completed orders rather than kept as a counter, so a
-- corrected or refunded order moves the tier back down on its own. §17.8 asks
-- for the progress to be *visible* ("$2,400 more to reach Gold"), which is why
-- `customer_tier` returns the next tier and the distance to it rather than just
-- a label.
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.settings (key, value) values (
  'customer_tiers',
  jsonb_build_array(
    jsonb_build_object('key','standard','from_irt',0,           'platform_bps',25),
    jsonb_build_object('key','silver',  'from_irt',2000000000,  'platform_bps',20),
    jsonb_build_object('key','gold',    'from_irt',10000000000, 'platform_bps',15),
    jsonb_build_object('key','platinum','from_irt',50000000000, 'platform_bps',10)
  )
) on conflict (key) do nothing;

create or replace function public.customer_tiers()
returns jsonb language sql stable security definer set search_path = public as $$
  select coalesce((select value from public.settings where key = 'customer_tiers'), '[]'::jsonb);
$$;

create or replace function public.customer_volume_irt(p_user uuid)
returns bigint language sql stable security definer set search_path = public as $$
  select coalesce(sum(
    case when o.send_currency = 'IRT' then o.send_amount_minor else o.receive_amount_minor end
  ), 0)::bigint
    from public.orders o
   where o.customer_id = p_user and o.state = 'completed' and o.deleted_at is null;
$$;

create or replace function public.customer_tier(p_user uuid default null)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare
  v_user uuid := coalesce(p_user, auth.uid());
  v_volume bigint;
  v_tiers jsonb := public.customer_tiers();
  v_current jsonb;
  v_next jsonb;
  t jsonb;
begin
  if v_user is null then return jsonb_build_object('tier', 'standard'); end if;
  v_volume := public.customer_volume_irt(v_user);

  for t in select * from jsonb_array_elements(v_tiers) loop
    if v_volume >= (t->>'from_irt')::bigint then
      v_current := t;
    elsif v_next is null then
      v_next := t;
    end if;
  end loop;

  return jsonb_build_object(
    'tier', coalesce(v_current->>'key', 'standard'),
    'platform_bps', coalesce((v_current->>'platform_bps')::int, 25),
    'volume_irt', v_volume,
    'next', v_next,
    'to_next_irt', case when v_next is null then null
                        else (v_next->>'from_irt')::bigint - v_volume end
  );
end $$;

revoke all on function public.customer_tiers() from public, anon, authenticated;
revoke all on function public.customer_volume_irt(uuid) from public, anon, authenticated;
revoke all on function public.customer_tier(uuid) from public, anon, authenticated;
grant execute on function public.customer_tiers() to anon, authenticated;
grant execute on function public.customer_tier(uuid) to authenticated;

-- ─────────────────────────────────────────────────────────────────────────────
-- C. Referrals (§17.9)
--
-- "Reward on the referee's first completed order" — so the reward is not
-- granted when the code is entered, and the claim itself is refused once the
-- referee has already transacted. Otherwise the program pays for customers it
-- did not bring.
-- ─────────────────────────────────────────────────────────────────────────────

create table public.referrals (
  id uuid primary key default gen_random_uuid(),
  referrer_id uuid not null references public.profiles (id),
  referee_id uuid not null references public.profiles (id) unique,
  code text not null,
  rewarded_at timestamptz,
  created_at timestamptz not null default now(),
  check (referrer_id <> referee_id)
);
alter table public.referrals enable row level security;
create policy referrals_own on public.referrals
  for select using (referrer_id = auth.uid() or referee_id = auth.uid() or public.is_platform_staff());
create trigger t_referrals_no_delete before delete on public.referrals
  for each row execute function public.forbid_delete();
create trigger t_referrals_audit after insert or update on public.referrals
  for each row execute function public.audit_row();

create or replace function public.referral_claim(p_code text)
returns boolean language plpgsql security definer set search_path = public as $$
declare v_referrer uuid; v_code text := upper(btrim(coalesce(p_code, '')));
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;
  if v_code = '' then return false; end if;

  select id into v_referrer from public.profiles where referral_code = v_code;
  if v_referrer is null or v_referrer = auth.uid() then return false; end if;
  if exists (select 1 from public.referrals where referee_id = auth.uid()) then return false; end if;
  if exists (select 1 from public.orders
              where customer_id = auth.uid() and state = 'completed') then return false; end if;

  insert into public.referrals (referrer_id, referee_id, code)
  values (v_referrer, auth.uid(), v_code)
  on conflict (referee_id) do nothing;
  return true;
end $$;

create or replace function public.referral_settle()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.state = 'completed' and old.state is distinct from 'completed' then
    update public.referrals
       set rewarded_at = now()
     where referee_id = new.customer_id and rewarded_at is null;
  end if;
  return null;
end $$;

create trigger t_orders_referral_settle
  after update of state on public.orders
  for each row execute function public.referral_settle();

revoke all on function public.referral_claim(text) from public, anon, authenticated;
revoke all on function public.referral_settle() from public, anon, authenticated;
grant execute on function public.referral_claim(text) to authenticated;
